all:
    hosts:
        full-node-1:
            ansible_host: 35.20.39.58
            ansible_user: polkadot
        full-node-2:
            ansible_host: 95.216.38.25
            ansible_user: polkadot


