
- name: Download the polkadot binary
  ansible.builtin.get_url:
    url: "{{ polkadot_base_url }}/polkadot"
    dest: /tmp/polkadot
    mode: "0755"

- name: Download polkadot-execute-worker binary
  ansible.builtin.get_url:
    url: "{{ polkadot_base_url }}/polkadot-execute-worker"
    dest: /tmp/polkadot-execute-worker
    mode: "0755"

- name: Download polkadot-prepare-worker binary
  ansible.builtin.get_url:
    url: "{{ polkadot_base_url }}/polkadot-prepare-worker"
    dest: /tmp/polkadot-prepare-worker
    mode: "0755"

- name: Move each polkadot file from /tmp to /opt/polkadot
  ansible.builtin.command: mv {{ item.src }} {{ item.dest }}
  loop:
    - { src: "/tmp/polkadot", dest: "/opt/polkadot/polkadot" }
    - { src: "/tmp/polkadot-execute-worker", dest: "/opt/polkadot/polkadot-execute-worker" }
    - { src: "/tmp/polkadot-prepare-worker", dest: "/opt/polkadot/polkadot-prepare-worker" }
  become: true

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure the Polkadot node service is running
  ansible.builtin.systemd:
    name: polkadot
    state: started
    enabled: true
